services:
  - type: web
    name: softpos-backend
    env: python
    plan: free
    region: oregon
    buildCommand: cd services/api && pip install -r requirements.txt
    startCommand: cd services/api && uvicorn app.main_simple:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        generateValue: true
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: softpos-db
    plan: free
    region: oregon