"""Initial payment tables

Revision ID: 001
Revises:
Create Date: 2025-09-21 02:51:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('mcc', sa.String(length=4), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('settlement_schedule', sa.String(length=20), nullable=False),
    sa.Column('default_fee_plan_id', sa.String(length=50), nullable=True),
    sa.Column('per_transaction_limit_minor', sa.Integer(), nullable=False),
    sa.Column('daily_volume_limit_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_intents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ephemeral_key', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('capture_mode', sa.String(length=20), nullable=True),
    sa.Column('tip_minor', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheme', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('auth_code', sa.String(length=20), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tip_minor', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('emv_payload', sa.Text(), nullable=True),
    sa.Column('attestation', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('payment_intents')
    op.drop_table('merchants')
    # ### end Alembic commands ###